### PR TITLE
create default z-index and check all modals

### PR DESCRIPTION
**Pull request by be-ndee**
I had the problem, that my first opened modal had the `layerPosition=-Infinity` and so calling the `open()` method with `true` to open the modal at the top of the modal stack didn't work. With this fix, the `layerPosition` has a default value as minimum (1042 because of 1041+1).

### CODE REVIEW

**Comment by maximelafarie** [comment]
Thank you for this PR @be-ndee! I'm currently looking at it.

**Comment by be-ndee** [comment]
What's the current progress of this pr?

**Comment by maximelafarie** [comment]
Thank you @be-ndee, I'll update the npm package after CI passed.

**Comment by maximelafarie** [comment]
Sorry for late answer. Your PR has been released into `v5.0.0`. Happy coding! 🖖

**Pull request merged**
