### PR TITLE
Fix visible attribute

### PR DESCRIPTION
**Pull request by khylias**
#108

### CODE REVIEW

**Comment by lkostrowski** [comment]
Hi guys, this one looks very simple. Can you merge it? ;)

**Comment by maximelafarie** [comment]
@lkostrowski It has been merged! 🎉 
I will assign a PR to @khylias with other fixes then push a new library version! 😉

**Comment by therepo90** [comment]
It still does not work. Only for initial attribute but when specificed with binding it does not work.

**Comment by lkostrowski** [comment]
Hm I think there should be trigger on onChanges hook as well

I will try to fix it during the weekend

**Comment by therepo90** [comment]
Not to mention ngif, getvisiblemodals not working. Also no api for modal .isOpen makes me abandon this lib sry

**Comment by maximelafarie** [comment]
@lkostrowski thank you very much, I'll also deep dive into this issue. 🤔 

@therepo90 We'll go beyond that unproductive comment. See ya! ✋

**Pull request merged**
